// Add secret images here.
export const mySecrets = {
  // T2: Running Interference
  'SEC_t2_interference_01': require('@/assets/images/secrets/t2_interference_01.png'),
  'SEC_t2_interference_02': require('@/assets/images/secrets/t2_interference_02.png'),
  'SEC_t2_interference_03': require('@/assets/images/secrets/t2_interference_03.png'),
  // T2: Shipping ... and Receiving
  'SEC_t2_shipping_01': require('@/assets/images/secrets/t2_shipping_01.png'),
  'SEC_t2_shipping_02': require('@/assets/images/secrets/t2_shipping_02.png'),
  'SEC_t2_shipping_03': require('@/assets/images/secrets/t2_shipping_03.png'),
  'SEC_t2_shipping_04': require('@/assets/images/secrets/t2_shipping_04.png'),
  'SEC_t2_shipping_05': require('@/assets/images/secrets/t2_shipping_05.png'),
  'SEC_t2_shipping_06a': require('@/assets/images/secrets/t2_shipping_06a.png'),
  'SEC_t2_shipping_06b': require('@/assets/images/secrets/t2_shipping_06b.png'),
  'SEC_t2_shipping_07': require('@/assets/images/secrets/t2_shipping_07.png'),
  'SEC_t2_shipping_08': require('@/assets/images/secrets/t2_shipping_08.png'),
  'SEC_t2_shipping_09': require('@/assets/images/secrets/t2_shipping_09.png'),
  'SEC_t2_shipping_10': require('@/assets/images/secrets/t2_shipping_10.png'),
  'SEC_t2_shipping_11': require('@/assets/images/secrets/t2_shipping_11.png'),
  'SEC_t2_shipping_12': require('@/assets/images/secrets/t2_shipping_12.png'),
  'SEC_t2_shipping_13': require('@/assets/images/secrets/t2_shipping_13.png'),
  'SEC_t2_shipping_14': require('@/assets/images/secrets/t2_shipping_14.png'),
  // T2: Framed
  'SEC_t2_framed_01a': require('@/assets/images/secrets/t2_framed_01a.png'),
  'SEC_t2_framed_01b': require('@/assets/images/secrets/t2_framed_01b.png'),
  'SEC_t2_framed_02a': require('@/assets/images/secrets/t2_framed_02a.png'),
  'SEC_t2_framed_02b': require('@/assets/images/secrets/t2_framed_02b.png'),
  'SEC_t2_framed_03': require('@/assets/images/secrets/t2_framed_03.png'),
  'SEC_t2_framed_04': require('@/assets/images/secrets/t2_framed_04.png'),
  'SEC_t2_framed_05a': require('@/assets/images/secrets/t2_framed_05a.png'),
  'SEC_t2_framed_05b': require('@/assets/images/secrets/t2_framed_05b.png'),
  'SEC_t2_framed_06a': require('@/assets/images/secrets/t2_framed_06a.png'),
  'SEC_t2_framed_06b': require('@/assets/images/secrets/t2_framed_06b.png'),
  'SEC_t2_framed_07a': require('@/assets/images/secrets/t2_framed_07a.png'),
  'SEC_t2_framed_07b': require('@/assets/images/secrets/t2_framed_07b.png'),
  'SEC_t2_framed_08a': require('@/assets/images/secrets/t2_framed_08a.png'),
  'SEC_t2_framed_08b': require('@/assets/images/secrets/t2_framed_08b.png'),
  'SEC_t2_framed_09a': require('@/assets/images/secrets/t2_framed_09a.png'),
  'SEC_t2_framed_09b': require('@/assets/images/secrets/t2_framed_09b.png'),
  // T2: Eavesdropping
  'SEC_t2_eavesdropping_01': require('@/assets/images/secrets/t2_eavesdropping_01.png'),
  // T2: First City Bank and Trust
  'SEC_t2_bank_01': require('@/assets/images/secrets/t2_bank_01.png'),
  'SEC_t2_bank_02': require('@/assets/images/secrets/t2_bank_02.png'),
  // T2: Blackmail
  'SEC_t2_blackmail_01': require('@/assets/images/secrets/t2_blackmail_01.png'),
  'SEC_t2_blackmail_02': require('@/assets/images/secrets/t2_blackmail_02.png'),
  'SEC_t2_blackmail_03a': require('@/assets/images/secrets/t2_blackmail_03a.png'),
  'SEC_t2_blackmail_03b': require('@/assets/images/secrets/t2_blackmail_03b.png'),
  'SEC_t2_blackmail_04': require('@/assets/images/secrets/t2_blackmail_04.png'),
  'SEC_t2_blackmail_05a': require('@/assets/images/secrets/t2_blackmail_05a.png'),
  'SEC_t2_blackmail_05b': require('@/assets/images/secrets/t2_blackmail_05b.png'),
  'SEC_t2_blackmail_06': require('@/assets/images/secrets/t2_blackmail_06.png'),
  // T2: Trace the Courier
  'SEC_t2_courier_01a': require('@/assets/images/secrets/t2_courier_01a.png'),
  'SEC_t2_courier_01b': require('@/assets/images/secrets/t2_courier_01b.png'),
  // T2: Life of the Party
  'SEC_t2_party_01': require('@/assets/images/secrets/t2_party_01.png'),
  'SEC_t2_party_02': require('@/assets/images/secrets/t2_party_02.png'),
  'SEC_t2_party_03': require('@/assets/images/secrets/t2_party_03.png'),
  'SEC_t2_party_04': require('@/assets/images/secrets/t2_party_04.png'),
  'SEC_t2_party_05': require('@/assets/images/secrets/t2_party_05.png'),
  'SEC_t2_party_06': require('@/assets/images/secrets/t2_party_06.png'),
  'SEC_t2_party_07': require('@/assets/images/secrets/t2_party_07.png'),
  // T2: Precious Cargo
  'SEC_t2_cargo_01': require('@/assets/images/secrets/t2_cargo_01.png'),
  // T2: Kidnap
  'SEC_t2_kidnap_01': require('@/assets/images/secrets/t2_kidnap_01.png'),
  // T2: Casing the Joint
  'SEC_t2_casing_01a': require('@/assets/images/secrets/t2_casing_01a.png'),
  'SEC_t2_casing_01b': require('@/assets/images/secrets/t2_casing_01b.png'),
  'SEC_t2_casing_02a': require('@/assets/images/secrets/t2_casing_02a.png'),
  'SEC_t2_casing_02b': require('@/assets/images/secrets/t2_casing_02b.png'),
  'SEC_t2_casing_03': require('@/assets/images/secrets/t2_casing_03.png'),
  'SEC_t2_casing_04a': require('@/assets/images/secrets/t2_casing_04a.png'),
  'SEC_t2_casing_04b': require('@/assets/images/secrets/t2_casing_04b.png'),
  'SEC_t2_casing_04c': require('@/assets/images/secrets/t2_casing_04c.png'),
  'SEC_t2_casing_04d': require('@/assets/images/secrets/t2_casing_04d.png'),
  'SEC_t2_casing_04e': require('@/assets/images/secrets/t2_casing_04e.png'),
  'SEC_t2_casing_05a': require('@/assets/images/secrets/t2_casing_05a.png'),
  'SEC_t2_casing_05b': require('@/assets/images/secrets/t2_casing_05b.png'),
  'SEC_t2_casing_05c': require('@/assets/images/secrets/t2_casing_05c.png'),
  'SEC_t2_casing_05d': require('@/assets/images/secrets/t2_casing_05d.png'),
  'SEC_t2_casing_05e': require('@/assets/images/secrets/t2_casing_05e.png'),
  'SEC_t2_casing_06a': require('@/assets/images/secrets/t2_casing_06a.png'),
  'SEC_t2_casing_06b': require('@/assets/images/secrets/t2_casing_06b.png'),
  'SEC_t2_casing_07a': require('@/assets/images/secrets/t2_casing_07a.png'),
  'SEC_t2_casing_07b': require('@/assets/images/secrets/t2_casing_07b.png'),
  'SEC_t2_casing_07c': require('@/assets/images/secrets/t2_casing_07c.png'),
  'SEC_t2_casing_07d': require('@/assets/images/secrets/t2_casing_07d.png'),
  'SEC_t2_casing_08': require('@/assets/images/secrets/t2_casing_08.png'),
  'SEC_t2_casing_09a': require('@/assets/images/secrets/t2_casing_09a.png'),
  'SEC_t2_casing_09b': require('@/assets/images/secrets/t2_casing_09b.png'),
  // T2: Masks
  'SEC_t2_masks_01a': require('@/assets/images/secrets/t2_masks_01a.png'),
  'SEC_t2_masks_01b': require('@/assets/images/secrets/t2_masks_01b.png'),
  'SEC_t2_masks_02a': require('@/assets/images/secrets/t2_masks_02a.png'),
  'SEC_t2_masks_02b': require('@/assets/images/secrets/t2_masks_02b.png'),
  'SEC_t2_masks_03': require('@/assets/images/secrets/t2_masks_03.png'),
  'SEC_t2_masks_04a': require('@/assets/images/secrets/t2_masks_04a.png'),
  'SEC_t2_masks_04b': require('@/assets/images/secrets/t2_masks_04b.png'),
  'SEC_t2_masks_04c': require('@/assets/images/secrets/t2_masks_04c.png'),
  'SEC_t2_masks_04d': require('@/assets/images/secrets/t2_masks_04d.png'),
  'SEC_t2_masks_04e': require('@/assets/images/secrets/t2_masks_04e.png'),
  'SEC_t2_masks_05a': require('@/assets/images/secrets/t2_masks_05a.png'),
  'SEC_t2_masks_05b': require('@/assets/images/secrets/t2_masks_05b.png'),
  'SEC_t2_masks_05c': require('@/assets/images/secrets/t2_masks_05c.png'),
  'SEC_t2_masks_05d': require('@/assets/images/secrets/t2_masks_05d.png'),
  'SEC_t2_masks_05e': require('@/assets/images/secrets/t2_masks_05e.png'),
  'SEC_t2_masks_06a': require('@/assets/images/secrets/t2_masks_06a.png'),
  'SEC_t2_masks_06b': require('@/assets/images/secrets/t2_masks_06b.png'),
  'SEC_t2_masks_07a': require('@/assets/images/secrets/t2_masks_07a.png'),
  'SEC_t2_masks_07b': require('@/assets/images/secrets/t2_masks_07b.png'),
  'SEC_t2_masks_07c': require('@/assets/images/secrets/t2_masks_07c.png'),
  'SEC_t2_masks_07d': require('@/assets/images/secrets/t2_masks_07d.png'),
  'SEC_t2_masks_08': require('@/assets/images/secrets/t2_masks_08.png'),
  'SEC_t2_masks_09a': require('@/assets/images/secrets/t2_masks_09a.png'),
  'SEC_t2_masks_09b': require('@/assets/images/secrets/t2_masks_09b.png'),
  'SEC_t2_masks_10a': require('@/assets/images/secrets/t2_masks_10a.png'),
  'SEC_t2_masks_10b': require('@/assets/images/secrets/t2_masks_10b.png'),
  'SEC_t2_masks_11a': require('@/assets/images/secrets/t2_masks_11a.png'),
  'SEC_t2_masks_11b': require('@/assets/images/secrets/t2_masks_11b.png'),
  'SEC_t2_masks_12a': require('@/assets/images/secrets/t2_masks_12a.png'),
  'SEC_t2_masks_12b': require('@/assets/images/secrets/t2_masks_12b.png'),
  // T2: Sabotage at Soulforge
  'SEC_t2_soulforge_01': require('@/assets/images/secrets/t2_soulforge_01.png'),
  'SEC_t2_soulforge_02': require('@/assets/images/secrets/t2_soulforge_02.png'),
  'SEC_t2_soulforge_03': require('@/assets/images/secrets/t2_soulforge_03.png'),
  'SEC_t2_soulforge_04': require('@/assets/images/secrets/t2_soulforge_04.png'),
  // T2: The Unwelcome Guest (Demo)
  'SEC_t2_guest_01': require('@/assets/images/secrets/t2_guest_01.png'),
  'SEC_t2_guest_02': require('@/assets/images/secrets/t2_guest_02.png'),
  'SEC_t2_guest_03': require('@/assets/images/secrets/t2_guest_03.png'),
  'SEC_t2_guest_04': require('@/assets/images/secrets/t2_guest_04.png'),

  // FM: The Art of Thievery
  'SEC_fm_artthievery_01': require('@/assets/images/secrets/fm_artthievery_01.png'),
  'SEC_fm_artthievery_02': require('@/assets/images/secrets/fm_artthievery_02.png'),
  'SEC_fm_artthievery_03a': require('@/assets/images/secrets/fm_artthievery_03a.png'),
  'SEC_fm_artthievery_03b': require('@/assets/images/secrets/fm_artthievery_03b.png'),
  'SEC_fm_artthievery_04a': require('@/assets/images/secrets/fm_artthievery_04a.png'),
  'SEC_fm_artthievery_04b': require('@/assets/images/secrets/fm_artthievery_04b.png'),
  'SEC_fm_artthievery_04c': require('@/assets/images/secrets/fm_artthievery_04c.png'),
  'SEC_fm_artthievery_05a': require('@/assets/images/secrets/fm_artthievery_05a.png'),
  'SEC_fm_artthievery_05b': require('@/assets/images/secrets/fm_artthievery_05b.png'),
  'SEC_fm_artthievery_05c': require('@/assets/images/secrets/fm_artthievery_05c.png'),
  'SEC_fm_artthievery_05d': require('@/assets/images/secrets/fm_artthievery_05d.png'),
  'SEC_fm_artthievery_06a': require('@/assets/images/secrets/fm_artthievery_06a.png'),
  'SEC_fm_artthievery_06b': require('@/assets/images/secrets/fm_artthievery_06b.png'),
  'SEC_fm_artthievery_07a': require('@/assets/images/secrets/fm_artthievery_07a.png'),
  'SEC_fm_artthievery_07b': require('@/assets/images/secrets/fm_artthievery_07b.png'),
  'SEC_fm_artthievery_08a': require('@/assets/images/secrets/fm_artthievery_08a.png'),
  'SEC_fm_artthievery_08b': require('@/assets/images/secrets/fm_artthievery_08b.png'),
  'SEC_fm_artthievery_09': require('@/assets/images/secrets/fm_artthievery_09.png'),
  'SEC_fm_artthievery_10a': require('@/assets/images/secrets/fm_artthievery_10a.png'),
  'SEC_fm_artthievery_10b': require('@/assets/images/secrets/fm_artthievery_10b.png'),
  'SEC_fm_artthievery_11a': require('@/assets/images/secrets/fm_artthievery_11a.png'),
  'SEC_fm_artthievery_11b': require('@/assets/images/secrets/fm_artthievery_11b.png'),
  'SEC_fm_artthievery_12': require('@/assets/images/secrets/fm_artthievery_12.png'),
  'SEC_fm_artthievery_13a': require('@/assets/images/secrets/fm_artthievery_13a.png'),
  'SEC_fm_artthievery_13b': require('@/assets/images/secrets/fm_artthievery_13b.png'),
  'SEC_fm_artthievery_14': require('@/assets/images/secrets/fm_artthievery_14.png'),
  'SEC_fm_artthievery_15': require('@/assets/images/secrets/fm_artthievery_15.png'),
  'SEC_fm_artthievery_16': require('@/assets/images/secrets/fm_artthievery_16.png'),
  'SEC_fm_artthievery_17': require('@/assets/images/secrets/fm_artthievery_17.png'),
  // FM: The Burrick's Head Inn
  'SEC_fm_burrickhead_01': require('@/assets/images/secrets/fm_burrickhead_01.png'),
  'SEC_fm_burrickhead_02': require('@/assets/images/secrets/fm_burrickhead_02.png'),
  'SEC_fm_burrickhead_03': require('@/assets/images/secrets/fm_burrickhead_03.png'),
  'SEC_fm_burrickhead_04': require('@/assets/images/secrets/fm_burrickhead_04.png'),
  // FM: Complicated Cargo
  'SEC_fm_cargo_01': require('@/assets/images/secrets/fm_cargo_01.png'),
  'SEC_fm_cargo_02': require('@/assets/images/secrets/fm_cargo_02.png'),
  'SEC_fm_cargo_03': require('@/assets/images/secrets/fm_cargo_03.png'),
  'SEC_fm_cargo_04': require('@/assets/images/secrets/fm_cargo_04.png'),
  'SEC_fm_cargo_05': require('@/assets/images/secrets/fm_cargo_05.png'),
  'SEC_fm_cargo_06': require('@/assets/images/secrets/fm_cargo_06.png'),
  'SEC_fm_cargo_07': require('@/assets/images/secrets/fm_cargo_07.png'),
  'SEC_fm_cargo_08': require('@/assets/images/secrets/fm_cargo_08.png'),
  'SEC_fm_cargo_09': require('@/assets/images/secrets/fm_cargo_09.png'),
  // FM: Durant
  'SEC_fm_durant_01': require('@/assets/images/secrets/fm_durant_01.png'),
  'SEC_fm_durant_02': require('@/assets/images/secrets/fm_durant_02.png'),
  // FM: Escape!
  'SEC_fm_ashton-escape_01': require('@/assets/images/secrets/fm_ashton-escape_01.png'),
  'SEC_fm_ashton-escape_02': require('@/assets/images/secrets/fm_ashton-escape_02.png'),
  'SEC_fm_ashton-escape_03': require('@/assets/images/secrets/fm_ashton-escape_03.png'),
  // FM: Hidden Agenda
  'SEC_fm_agenda_01': require('@/assets/images/secrets/fm_agenda_01.png'),
  'SEC_fm_agenda_02': require('@/assets/images/secrets/fm_agenda_02.png'),
  'SEC_fm_agenda_03': require('@/assets/images/secrets/fm_agenda_03.png'),
  'SEC_fm_agenda_04': require('@/assets/images/secrets/fm_agenda_04.png'),
  // FM: Into the Maelstrom
  'SEC_fm_maelstrom_01': require('@/assets/images/secrets/fm_maelstrom_01.png'),
  'SEC_fm_maelstrom_02': require('@/assets/images/secrets/fm_maelstrom_02.png'),
  'SEC_fm_maelstrom_03': require('@/assets/images/secrets/fm_maelstrom_03.png'),
  // FM: The Inverted Manse
  'SEC_fm_spirit-manse_01': require('@/assets/images/secrets/fm_spirit-manse_01.png'),
  // FM: Lord James' Retreat
  'SEC_fm_retreat_01': require('@/assets/images/secrets/fm_retreat_01.png'),
  'SEC_fm_retreat_02': require('@/assets/images/secrets/fm_retreat_02.png'),
  'SEC_fm_retreat_03': require('@/assets/images/secrets/fm_retreat_03.png'),
  // FM: The Night Before Christmas
  'SEC_fm_nightchristmas_01': require('@/assets/images/secrets/fm_nightchristmas_01.png'),
  // FM: A Night's Stroll
  'SEC_fm_ashton-stroll_01': require('@/assets/images/secrets/fm_ashton-stroll_01.png'),
  'SEC_fm_ashton-stroll_02': require('@/assets/images/secrets/fm_ashton-stroll_02.png'),
  'SEC_fm_ashton-stroll_03': require('@/assets/images/secrets/fm_ashton-stroll_03.png'),
  'SEC_fm_ashton-stroll_04': require('@/assets/images/secrets/fm_ashton-stroll_04.png'),
  'SEC_fm_ashton-stroll_05': require('@/assets/images/secrets/fm_ashton-stroll_05.png'),
  'SEC_fm_ashton-stroll_06': require('@/assets/images/secrets/fm_ashton-stroll_06.png'),
  'SEC_fm_ashton-stroll_07': require('@/assets/images/secrets/fm_ashton-stroll_07.png'),
  // FM: Ominous Bequest
  'SEC_fm_xedormicost-bequest_01': require('@/assets/images/secrets/fm_xedormicost-bequest_01.png'),
  'SEC_fm_xedormicost-bequest_02a': require('@/assets/images/secrets/fm_xedormicost-bequest_02a.png'),
  'SEC_fm_xedormicost-bequest_02b': require('@/assets/images/secrets/fm_xedormicost-bequest_02b.png'),
  'SEC_fm_xedormicost-bequest_02c': require('@/assets/images/secrets/fm_xedormicost-bequest_02c.png'),
  'SEC_fm_xedormicost-bequest_03a': require('@/assets/images/secrets/fm_xedormicost-bequest_03a.png'),
  'SEC_fm_xedormicost-bequest_03b': require('@/assets/images/secrets/fm_xedormicost-bequest_03b.png'),
  'SEC_fm_xedormicost-bequest_04': require('@/assets/images/secrets/fm_xedormicost-bequest_04.png'),
  'SEC_fm_xedormicost-bequest_05': require('@/assets/images/secrets/fm_xedormicost-bequest_05.png'),
  'SEC_fm_xedormicost-bequest_06': require('@/assets/images/secrets/fm_xedormicost-bequest_06.png'),
  'SEC_fm_xedormicost-bequest_07': require('@/assets/images/secrets/fm_xedormicost-bequest_07.png'),
  'SEC_fm_xedormicost-bequest_08': require('@/assets/images/secrets/fm_xedormicost-bequest_08.png'),
  // FM: Revenge
  'SEC_fm_ashton-revenge_01': require('@/assets/images/secrets/fm_ashton-revenge_01.png'),
  'SEC_fm_ashton-revenge_02': require('@/assets/images/secrets/fm_ashton-revenge_02.png'),
  'SEC_fm_ashton-revenge_03': require('@/assets/images/secrets/fm_ashton-revenge_03.png'),
  'SEC_fm_ashton-revenge_04': require('@/assets/images/secrets/fm_ashton-revenge_04.png'),
  'SEC_fm_ashton-revenge_05': require('@/assets/images/secrets/fm_ashton-revenge_05.png'),
  // FM: Rowena's Curse
  'SEC_fm_rowena_01': require('@/assets/images/secrets/fm_rowena_01.png'),
  'SEC_fm_rowena_02': require('@/assets/images/secrets/fm_rowena_02.png'),
  'SEC_fm_rowena_03a': require('@/assets/images/secrets/fm_rowena_03a.png'),
  'SEC_fm_rowena_03b': require('@/assets/images/secrets/fm_rowena_03b.png'),
  'SEC_fm_rowena_04': require('@/assets/images/secrets/fm_rowena_04.png'),
  'SEC_fm_rowena_05a': require('@/assets/images/secrets/fm_rowena_05a.png'),
  'SEC_fm_rowena_05b': require('@/assets/images/secrets/fm_rowena_05b.png'),
  'SEC_fm_rowena_06': require('@/assets/images/secrets/fm_rowena_06.png'),
  'SEC_fm_rowena_07': require('@/assets/images/secrets/fm_rowena_07.png'),
  'SEC_fm_rowena_08': require('@/assets/images/secrets/fm_rowena_08.png'),
  // FM: So Long Hammers
  'SEC_fm_solong_01': require('@/assets/images/secrets/fm_solong_01.png'),
  'SEC_fm_solong_02': require('@/assets/images/secrets/fm_solong_02.png'),
  'SEC_fm_solong_03': require('@/assets/images/secrets/fm_solong_03.png'),
  'SEC_fm_solong_04': require('@/assets/images/secrets/fm_solong_04.png'),
  'SEC_fm_solong_05': require('@/assets/images/secrets/fm_solong_05.png'),
  'SEC_fm_solong_06': require('@/assets/images/secrets/fm_solong_06.png'),
  'SEC_fm_solong_07': require('@/assets/images/secrets/fm_solong_07.png'),
  /// FM: Tales from the Cleft - Ladytaker
  'SEC_fm_cleft-ladytaker_01': require('@/assets/images/secrets/fm_cleft-ladytaker_01.png'),
  'SEC_fm_cleft-ladytaker_02': require('@/assets/images/secrets/fm_cleft-ladytaker_02.png'),
  'SEC_fm_cleft-ladytaker_03': require('@/assets/images/secrets/fm_cleft-ladytaker_03.png'),
  // FM: A Theft in High Towne
  'SEC_fm_thefthightowne_01': require('@/assets/images/secrets/fm_thefthightowne_01.png'),
  'SEC_fm_thefthightowne_02': require('@/assets/images/secrets/fm_thefthightowne_02.png'),
  // FM: Thieves' Highway
  'SEC_fm_highway_01': require('@/assets/images/secrets/fm_highway_01.png'),
  'SEC_fm_highway_02': require('@/assets/images/secrets/fm_highway_02.png'),
  'SEC_fm_highway_03': require('@/assets/images/secrets/fm_highway_03.png'),
  'SEC_fm_highway_04': require('@/assets/images/secrets/fm_highway_04.png'),
  'SEC_fm_highway_05': require('@/assets/images/secrets/fm_highway_05.png'),
  // FM: Through No Vault of My Own
  'SEC_fm_novault_01': require('@/assets/images/secrets/fm_novault_01.png'),
  // FM: Ultima Ratio
  'SEC_fm_forces-ultima_01': require('@/assets/images/secrets/fm_forces-ultima_01.png'),
  'SEC_fm_forces-ultima_02': require('@/assets/images/secrets/fm_forces-ultima_02.png'),
  'SEC_fm_forces-ultima_03': require('@/assets/images/secrets/fm_forces-ultima_03.png'),
  'SEC_fm_forces-ultima_04': require('@/assets/images/secrets/fm_forces-ultima_04.png'),
  'SEC_fm_forces-ultima_05': require('@/assets/images/secrets/fm_forces-ultima_05.png'),
  'SEC_fm_forces-ultima_06': require('@/assets/images/secrets/fm_forces-ultima_06.png'),
  'SEC_fm_forces-ultima_07': require('@/assets/images/secrets/fm_forces-ultima_07.png'),
  'SEC_fm_forces-ultima_08': require('@/assets/images/secrets/fm_forces-ultima_08.png'),
  'SEC_fm_forces-ultima_09': require('@/assets/images/secrets/fm_forces-ultima_09.png'),
  // FM: United Bank of Auldale
  'SEC_fm_united_01': require('@/assets/images/secrets/fm_united_01.png'),
  // FM: A Visit to Lord Ashton's
  'SEC_fm_ashton-visit_01': require('@/assets/images/secrets/fm_ashton-visit_01.png'),
  'SEC_fm_ashton-visit_02': require('@/assets/images/secrets/fm_ashton-visit_02.png'),
  'SEC_fm_ashton-visit_03': require('@/assets/images/secrets/fm_ashton-visit_03.png'),
  'SEC_fm_ashton-visit_04': require('@/assets/images/secrets/fm_ashton-visit_04.png'),
  'SEC_fm_ashton-visit_05': require('@/assets/images/secrets/fm_ashton-visit_05.png'),
  'SEC_fm_ashton-visit_06': require('@/assets/images/secrets/fm_ashton-visit_06.png'),
  'SEC_fm_ashton-visit_07': require('@/assets/images/secrets/fm_ashton-visit_07.png'),
  'SEC_fm_ashton-visit_08': require('@/assets/images/secrets/fm_ashton-visit_08.png'),
  // FM: Weak Links
  'SEC_fm_links_01': require('@/assets/images/secrets/fm_links_01.png'),
  'SEC_fm_links_02': require('@/assets/images/secrets/fm_links_02.png'),
  'SEC_fm_links_03a': require('@/assets/images/secrets/fm_links_03a.png'),
  'SEC_fm_links_03b': require('@/assets/images/secrets/fm_links_03b.png'),
  'SEC_fm_links_04': require('@/assets/images/secrets/fm_links_04.png'),
}
