// Add FM data for FM selection page here.
export const myFMs = {
  "sortAlpha": require('@/assets/categoryFMs.json'),
  "sortChrono": require('@/assets/campaignFMs.json')
}

// Add THIEF games here.
export const myGames = {
  "game_t1": "The Dark Project / Gold",
  "game_t2": "The Metal Age",
  "game_t3": "Deadly Shadows",
}

// Add years here.
export const myYears = {
  "y1999": 1999,
  "y2000": 2000,
  "y2001": 2001,
  "y2002": 2002,
  "y2003": 2003,
  "y2004": 2004,
  "y2005": 2005,
  "y2006": 2006,
  "y2007": 2007,
  "y2008": 2008,
  "y2009": 2009,
  "y2010": 2010,
  "y2011": 2011,
  "y2012": 2012,
}

// Add FM authors here.
export const myAuthors = {
  "auth_asylum": "AsyluM",
  "auth_balboa": "Balboa",
  "auth_bbb": "BBB",
  "auth_cardia": "Cardia",
  "auth_christine": "Christine",
  "auth_darkshadow": "DarkShadow",
  "auth_darthslair": "DarthsLair",
  "auth_eshaktaar": "Eshaktaar",
  "auth_gaetane": "Gaëtane",
  "auth_ghostshell": "Ghost in the Shell",
  "auth_gingerbreadman": "The Gingerbread Man",
  "auth_haplo": "Haplo",
  "auth_intruder": "intruder",
  "auth_john9818a": "john9818a",
  "auth_kozmala": "Kozmala",
  "auth_ladyrowena": "Lady Rowena",
  "auth_larryg": "LarryG",
  "auth_mazur": "Mazur",
  "auth_melan": "Melan",
  "auth_morrgan": "Morrgan",
  "auth_mxleader": "mxleader",
  "auth_namelessvoice": "Nameless Voice",
  "auth_psymh": "PsymH",
  "auth_purah": "Purah",
  "auth_oldfatburrick": "Ramirez's Old Fat Burrick",
  "auth_brethren": "Renault",
  "auth_rich": "RiCh",
  "auth_saturnine": "Saturnine",
  "auth_schwaa": "Schwaa",
  "auth_sharga": "Sharga",
  "auth_silentsleep": "SilentSleep",
  "auth_skacky": "Skacky",
  "auth_sledge": "Sledge",
  "auth_soultear": "Soul Tear",
  "auth_uncadonego": "Uncadonego",
  "auth_vigil": "Vigil",
  "auth_xorak": "Xorak",
  "auth_yandros": "Yandros",
  "auth_team_calendra": "Team Calendra",
  "auth_team_t2x": "Dark Engineering Guild",
  "auth_anon_": "[Anonymous]"
}

// Add FM protagonists here.
export const myProtagonists = {
  "protag_garrett": "Garrett",
  "protag_zaya": "Zaya",
  "protag_gellert": "Gellert",
  "protag_reuben": "Reuben",
  "protag_conall": "Conall",
  "protag_hume": "Hume",
  "protag_other": "[Other]",
}

// Add FM series & campaigns here.
export const myCampaigns = {
  "cam_calendra": "Calendra",
  "cam_spirit": "Spirit Stone",
  "cam_seventh": "The Seventh Crystal",
  "cam_ashton": "Lord Ashton",
  "cam_triad": "Xedormicost",
  "cam_t2x": "T2X - Shadows of the Metal Age",
  "cam_forces": "Element of Three Forces",
  "cam_below": "Hammer Relics",
  "cam_cleft": "Tales from the Cleft",
}

// Add FM contests here.
export const myContests = {
  "con_komag1": "Komag Contest 1",
  "con_komag2": "Komag Contest 2",
  "con_komag3": "Komag Contest 3",
  "con_komag4": "Komag Contest 4",
  "con_komag5": "Komag Contest 5",
  "con_water": "Water Contest",
  "con_ssr": "Small Stock Resource Contest",
  "con_cte": "Classic Thief Experience Contest",
  "con_anniv1_10": "Thief Anniversary Contest",
  "con_unpc": "No Pressure Contest",
  "con_svc": "Summer Vacation Contest",
  "con_reload1": "Reloaded Contest",
  "con_reload2": "Reloaded Contest 2",
}

// Add mission genres here.
export const myGenres = {
  "genre_burglar": "Burglary",
  "genre_heist": "Heist",
  "genre_salvage": "Salvage",
  "genre_assassin": "Assassination",
  "genre_sabotage": "Sabotage",
  "genre_frame": "Frame",
  "genre_blackmail": "Blackmail",
  "genre_investigate": "Investigation",
  "genre_mystery": "Mystery",
  "genre_deliver": "Delivery",
  "genre_rendezvous": "Rendezvous",
  "genre_trail": "Trail",
  "genre_rescue": "Rescue",
  "genre_escape": "Escape",
  "genre_ghost": "Ghost",
  "genre_timed": "Timed",
  "genre_puzzle": "Puzzle",
  "genre_horror": "Horror",
  "genre_scifi": "Sci-Fi",
  "genre_modern": "Modern",
  "genre_daytime": "Daytime",
  "genre_dusk": "Dusk",
  "genre_holiday": "Holiday",
}

// Add mission locations here.
export const myLocations = {
  "loc_mansion": "Mansion / Estate",
  "loc_castle": "Castle / Keep",
  "loc_streets": "City Streets",
  "loc_rooftops": "Rooftops",
  "loc_bank": "Bank",
  "loc_museum": "Museum",
  "loc_library": "Library",
  "loc_school": "School",
  "loc_theater": "Theater",
  "loc_restaurant": "Restaurant",
  "loc_tavern": "Tavern",
  "loc_hotel": "Hotel / Inn",
  "loc_brothel": "Brothel",
  "loc_casino": "Casino",
  "loc_police": "Police Station",
  "loc_prison": "Jail / Prison",
  "loc_tower": "Tower",
  "loc_hospital": "Hospital",
  "loc_church": "Church",
  "loc_cemetery": "Cemetery",
  "loc_catacombs": "Crypt / Catacombs",
  "loc_cityruins": "Ruined City",
  "loc_works": "Public Works",
  "loc_sewers": "Sewers",
  "loc_hideout": "Hideout",
  "loc_factory": "Factory",
  "loc_warehouse": "Warehouse",
  "loc_depot": "Depot / Train",
  "loc_docks": "Docks / Harbor",
  "loc_lighthouse": "Lighthouse",
  "loc_ship": "Ship / Vessel",
  "loc_river": "River / Canal",
  "loc_island": "Island",
  "loc_cave": "Cave / Tunnel",
  "loc_mountain": "Mountain / Valley",
  "loc_cottage": "Cottage",
  "loc_village": "Village",
  "loc_forest": "Forest",
  "loc_ancient": "Ancient Ruins",
  "loc_extra": "Extraplanar",
}

// Add enemy categories here.
export const myEnemies = {
  "npc_guards": "Guards",
  "npc_servants": "Servants",
  "npc_nobles": "Nobles",
  "npc_thieves": "Thieves",
  "npc_watch": "City Watch",
  "npc_hammerites": "Hammerites",
  "npc_mechanists": "Mechanists",
  "npc_pagans": "Pagans",
  "npc_keepers": "Keepers",
  "npc_mages": "Mages",
  "npc_zombies": "Zombies",
  "npc_haunts": "Haunts",
  "npc_ghosts": "Ghosts",
  "npc_undead": "Other Undead",
  "npc_spiders": "Spiders",
  "npc_burricks": "Burricks",
  "npc_beasts": "Maw Beasts",
  "npc_creatures": "Other Creatures",
  "npc_monsters": "Monsters",
  "npc_elementals": "Elementals",
  "npc_robots": "Robots",
}

// Add recurring characters here.
export const myCharacters = {
  "char_bafford": "Lord Bafford",
  "char_ramirez": "Ramirez",
  "char_downwind": "Downwind Thieves' Guild",
  "char_basso": "Basso",
  "char_jenivere": "Jenivere",
  "char_benny": "Benny",
  "char_truart": "Sheriff Truart",
  "char_karras": "Karras",
  "char_gamall": "Gamall",
}

// Add recurring items here.
export const myItems = {
  "item_basketball": "Basketball",
  "item_scepter": "Silver Scepter",
  "item_hand": "Hand of Glory",
  "item_goldbone": "Golden Bone",
  "item_heartsoul": "Mystic's Heart/Soul",
  "item_quintus": "Horn of Quintus",
  "item_poker": "Silver Fire Poker",
  "item_bracelet": "Silver Bracelet",
  "item_sapphirevase": "Sapphire Vase",
  "item_consword": "Constantine's Sword",
  "item_torc": "Serpentyle Torc",
  "item_magemedal": "Purple Medallion",
  "item_keepermedal": "Keeper Medallion",
  "item_flute": "Silver Flute",
  "item_holyhammer": "Holy Hammer",
  "item_talisman": "Talismans",
  "item_eye": "The Eye",
  "item_rosary": "Rosary Beads",
  "item_holysymbol": "Holy Symbol",
  "item_sunburst": "Explosive Charge",
  "item_chisel": "Builder's Chisel",
  //"item_dice": "Gold Dice",
  "item_cylinder": "Wax Cylinder",
  "item_spice": "Rare Spice Bag",
  "item_dewdrop": "Dewdrop",
  "item_ruby": "Ruby Stone",
  "item_globe": "Navigation Globe",
  "item_rustgas": "Rust Gas Canister",
  "item_drillbit": "Diamond Drill Bit",
  "item_premask": "Large Precursor Mask",
  "item_cultivator": "Cultivator",
  "item_gear": "Gold Gear",
}

// Add FM filter options here.
export const filterFM = {
  "games": [
    {"key": "0", "value": myGames.game_t1},
    {"key": "1", "value": myGames.game_t2},
    //{"key": "2", "value": myGames.game_t3}
  ],
  "years": [
    {"key": "0", "value": myYears.y1999},
    {"key": "1", "value": myYears.y2000},
    {"key": "2", "value": myYears.y2001},
    {"key": "3", "value": myYears.y2002},
    {"key": "4", "value": myYears.y2003},
    {"key": "5", "value": myYears.y2004},
    {"key": "6", "value": myYears.y2005},
    {"key": "7", "value": myYears.y2006},
    {"key": "8", "value": myYears.y2007},
    {"key": "9", "value": myYears.y2008},
    {"key": "10", "value": myYears.y2009},
    {"key": "11", "value": myYears.y2010},
    {"key": "12", "value": myYears.y2011}
    //{"key": "13", "value": myYears.y2012}
  ],
  "authors": [
    {"key": "0", "value": myAuthors.auth_asylum},
    {"key": "1", "value": myAuthors.auth_balboa},
    //{"key": "2", "value": myAuthors.auth_bbb},
    //{"key": "3", "value": myAuthors.auth_cardia},
    {"key": "4", "value": myAuthors.auth_christine},
    {"key": "5", "value": myAuthors.auth_darkshadow},
    //{"key": "6", "value": myAuthors.auth_darthslair},
    //{"key": "7", "value": myAuthors.auth_eshaktaar},
    //{"key": "8", "value": myAuthors.auth_gaetane},
    {"key": "9", "value": myAuthors.auth_ghostshell},
    {"key": "10", "value": myAuthors.auth_gingerbreadman},
    //{"key": "11", "value": myAuthors.auth_haplo},
    {"key": "12", "value": myAuthors.auth_intruder},
    //{"key": "13", "value": myAuthors.auth_john9818a},
    //{"key": "14", "value": myAuthors.auth_kozmala},
    //{"key": "15", "value": myAuthors.auth_ladyrowena},
    //{"key": "16", "value": myAuthors.auth_larryg},
    {"key": "17", "value": myAuthors.auth_mazur},
    {"key": "18", "value": myAuthors.auth_melan},
    {"key": "19", "value": myAuthors.auth_morrgan},
    {"key": "20", "value": myAuthors.auth_mxleader},
    //{"key": "21", "value": myAuthors.auth_namelessvoice},
    {"key": "22", "value": myAuthors.auth_psymh},
    {"key": "23", "value": myAuthors.auth_purah},
    {"key": "24", "value": myAuthors.auth_oldfatburrick},
    {"key": "25", "value": myAuthors.auth_brethren},
    {"key": "26", "value": myAuthors.auth_rich},
    {"key": "27", "value": myAuthors.auth_saturnine},
    //{"key": "28", "value": myAuthors.auth_schwaa},
    //{"key": "29", "value": myAuthors.auth_sharga},
    //{"key": "30", "value": myAuthors.auth_silentsleep},
    //{"key": "31", "value": myAuthors.auth_skacky},
    {"key": "32", "value": myAuthors.auth_sledge},
    //{"key": "33", "value": myAuthors.auth_soultear},
    {"key": "34", "value": myAuthors.auth_uncadonego},
    {"key": "35", "value": myAuthors.auth_vigil},
    //{"key": "36", "value": myAuthors.auth_xorak},
    {"key": "37", "value": myAuthors.auth_yandros},
    {"key": "38", "value": myAuthors.auth_team_calendra}
    //{"key": "39", "value": myAuthors.auth_team_t2x},
    //{"key": "40", "value": myAuthors.auth_anon_}
  ],
  "protagonists": [
    {"key": "0", "value": myProtagonists.protag_garrett},
    //{"key": "1", "value": myProtagonists.protag_zaya},
    //{"key": "2", "value": myProtagonists.protag_gellert},
    //{"key": "3", "value": myProtagonists.protag_reuben},
    //{"key": "4", "value": myProtagonists.protag_conall},
    //{"key": "5", "value": myProtagonists.protag_hume},
    {"key": "6", "value": myProtagonists.protag_other}
  ],
  "campaigns": [
    {"key": "0", "value": myCampaigns.cam_calendra},
    {"key": "1", "value": myCampaigns.cam_spirit},
    {"key": "2", "value": myCampaigns.cam_seventh},
    {"key": "3", "value": myCampaigns.cam_ashton},
    //{"key": "4", "value": myCampaigns.cam_triad},
    //{"key": "5", "value": myCampaigns.cam_t2x},
    {"key": "6", "value": myCampaigns.cam_forces},
    //{"key": "7", "value": myCampaigns.cam_below},
    {"key": "8", "value": myCampaigns.cam_cleft}
  ],
  "contests": [
    //{"key": "0", "value": myContests.con_komag1},
    //{"key": "1", "value": myContests.con_komag2},
    //{"key": "2", "value": myContests.con_komag3},
    {"key": "3", "value": myContests.con_komag4},
    {"key": "4", "value": myContests.con_komag5},
    {"key": "5", "value": myContests.con_water},
    {"key": "6", "value": myContests.con_ssr},
    {"key": "7", "value": myContests.con_cte},
    {"key": "8", "value": myContests.con_anniv1_10},
    {"key": "9", "value": myContests.con_unpc},
    //{"key": "10", "value": myContests.con_svc},
    {"key": "11", "value": myContests.con_reload1}
    //{"key": "12", "value": myContests.con_reload2}
  ],
  "genres": [
    {"key": "0", "value": myGenres.genre_burglar},
    {"key": "1", "value": myGenres.genre_heist},
    {"key": "2", "value": myGenres.genre_salvage},
    {"key": "3", "value": myGenres.genre_assassin},
    {"key": "4", "value": myGenres.genre_sabotage},
    {"key": "5", "value": myGenres.genre_frame},
    //{"key": "6", "value": myGenres.genre_blackmail},
    {"key": "7", "value": myGenres.genre_investigate},
    {"key": "8", "value": myGenres.genre_mystery},
    {"key": "9", "value": myGenres.genre_deliver},
    {"key": "10", "value": myGenres.genre_rendezvous},
    {"key": "11", "value": myGenres.genre_trail},
    {"key": "12", "value": myGenres.genre_rescue},
    {"key": "13", "value": myGenres.genre_escape},
    {"key": "14", "value": myGenres.genre_ghost},
    {"key": "15", "value": myGenres.genre_timed},
    {"key": "16", "value": myGenres.genre_puzzle},
    {"key": "17", "value": myGenres.genre_horror},
    //{"key": "18", "value": myGenres.genre_scifi},
    {"key": "19", "value": myGenres.genre_modern},
    {"key": "20", "value": myGenres.genre_daytime},
    {"key": "21", "value": myGenres.genre_dusk},
    {"key": "22", "value": myGenres.genre_holiday}
  ],
  "locations": [
    {"key": "0", "value": myLocations.loc_mansion},
    {"key": "1", "value": myLocations.loc_castle},
    {"key": "2", "value": myLocations.loc_streets},
    {"key": "3", "value": myLocations.loc_rooftops},
    {"key": "4", "value": myLocations.loc_bank},
    {"key": "5", "value": myLocations.loc_museum},
    {"key": "6", "value": myLocations.loc_library},
    //{"key": "7", "value": myLocations.loc_school},
    //{"key": "8", "value": myLocations.loc_theater},
    {"key": "9", "value": myLocations.loc_restaurant},
    {"key": "10", "value": myLocations.loc_tavern},
    {"key": "11", "value": myLocations.loc_hotel},
    {"key": "12", "value": myLocations.loc_brothel},
    {"key": "13", "value": myLocations.loc_casino},
    {"key": "14", "value": myLocations.loc_police},
    {"key": "15", "value": myLocations.loc_prison},
    {"key": "16", "value": myLocations.loc_tower},
    {"key": "17", "value": myLocations.loc_hospital},
    {"key": "18", "value": myLocations.loc_church},
    {"key": "19", "value": myLocations.loc_cemetery},
    {"key": "20", "value": myLocations.loc_catacombs},
    {"key": "21", "value": myLocations.loc_cityruins},
    {"key": "22", "value": myLocations.loc_works},
    {"key": "23", "value": myLocations.loc_sewers},
    {"key": "24", "value": myLocations.loc_hideout},
    {"key": "25", "value": myLocations.loc_factory},
    {"key": "26", "value": myLocations.loc_warehouse},
    //{"key": "27", "value": myLocations.loc_depot},
    {"key": "28", "value": myLocations.loc_docks},
    //{"key": "29", "value": myLocations.loc_lighthouse},
    {"key": "30", "value": myLocations.loc_ship},
    {"key": "31", "value": myLocations.loc_river},
    {"key": "32", "value": myLocations.loc_island},
    {"key": "33", "value": myLocations.loc_cave},
    {"key": "34", "value": myLocations.loc_mountain},
    {"key": "35", "value": myLocations.loc_cottage},
    {"key": "36", "value": myLocations.loc_village},
    {"key": "37", "value": myLocations.loc_forest},
    {"key": "38", "value": myLocations.loc_ancient}
    //{"key": "39", "value": myLocations.loc_extra}
  ],
  "enemies": [
    {"key": "0", "value": myEnemies.npc_guards},
    {"key": "1", "value": myEnemies.npc_servants},
    {"key": "2", "value": myEnemies.npc_nobles},
    {"key": "3", "value": myEnemies.npc_thieves},
    {"key": "4", "value": myEnemies.npc_watch},
    {"key": "5", "value": myEnemies.npc_hammerites},
    {"key": "6", "value": myEnemies.npc_mechanists},
    {"key": "7", "value": myEnemies.npc_pagans},
    {"key": "8", "value": myEnemies.npc_keepers},
    {"key": "9", "value": myEnemies.npc_mages},
    {"key": "10", "value": myEnemies.npc_zombies},
    {"key": "11", "value": myEnemies.npc_haunts},
    {"key": "12", "value": myEnemies.npc_ghosts},
    {"key": "13", "value": myEnemies.npc_undead},
    {"key": "14", "value": myEnemies.npc_spiders},
    {"key": "15", "value": myEnemies.npc_burricks},
    {"key": "16", "value": myEnemies.npc_beasts},
    {"key": "17", "value": myEnemies.npc_creatures},
    {"key": "18", "value": myEnemies.npc_monsters},
    {"key": "19", "value": myEnemies.npc_elementals},
    {"key": "20", "value": myEnemies.npc_robots}
  ],
  "characters": [
    {"key": "0", "value": myCharacters.char_bafford},
    //{"key": "1", "value": myCharacters.char_ramirez},
    {"key": "2", "value": myCharacters.char_downwind},
    {"key": "3", "value": myCharacters.char_basso},
    {"key": "4", "value": myCharacters.char_jenivere},
    {"key": "5", "value": myCharacters.char_benny}
    //{"key": "6", "value": myCharacters.char_truart},
    //{"key": "7", "value": myCharacters.char_karras},
    //{"key": "8", "value": myCharacters.char_gamall}
  ],
  "items": [
    {"key": "0", "value": myItems.item_basketball},
    {"key": "1", "value": myItems.item_scepter},
    {"key": "2", "value": myItems.item_hand},
    {"key": "3", "value": myItems.item_goldbone},
    {"key": "4", "value": myItems.item_heartsoul},
    {"key": "5", "value": myItems.item_quintus},
    {"key": "6", "value": myItems.item_poker},
    {"key": "7", "value": myItems.item_bracelet},
    {"key": "8", "value": myItems.item_sapphirevase},
    {"key": "9", "value": myItems.item_consword},
    {"key": "10", "value": myItems.item_torc},
    {"key": "11", "value": myItems.item_magemedal},
    {"key": "12", "value": myItems.item_keepermedal},
    {"key": "13", "value": myItems.item_flute},
    {"key": "14", "value": myItems.item_holyhammer},
    {"key": "15", "value": myItems.item_talisman},
    {"key": "16", "value": myItems.item_eye},
    {"key": "17", "value": myItems.item_rosary},
    {"key": "18", "value": myItems.item_holysymbol},
    {"key": "19", "value": myItems.item_sunburst},
    {"key": "20", "value": myItems.item_chisel},
    //{"key": "21", "value": myItems.item_dice},
    //{"key": "22", "value": myItems.item_cylinder},
    {"key": "23", "value": myItems.item_spice},
    {"key": "24", "value": myItems.item_dewdrop},
    {"key": "25", "value": myItems.item_ruby},
    {"key": "26", "value": myItems.item_globe},
    //{"key": "27", "value": myItems.item_rustgas},
    {"key": "28", "value": myItems.item_drillbit},
    {"key": "29", "value": myItems.item_premask},
    //{"key": "30", "value": myItems.item_cultivator},
    {"key": "31", "value": myItems.item_gear}
  ],
}
